spring.application.name=chatting-app
server.port=1000

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
spring.jpa.properties.hibernate.default_batch_fetch_size=${DEFAULT_BATCH_FETCH_SIZE:50}
